spring:
  jpa:
    hibernate:
      ddl-auto: none #create update none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k9a203.p.ssafy.io:3306/showeat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: showeat
    password: showeat1357

kafka:
  server: "k9a203.p.ssafy.io:9092"