spring:
  jpa:
    hibernate:
      ddl-auto: update #create update none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/showeat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: showeat
    password: 1234
  #redis
  data:
    redis:
      host: localhost
      port: 6379
  #security
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:3000/sign-in/loading

# TossPayments
payments:
  toss:
    test_client_api_key: test_ck_QbgMGZzorzyKv2BGY6djVl5E1em4
    test_secret_api_key: test_sk_Ba5PzR0ArnWLjDw7vPe18vmYnNeD
    success_url: http://localhost:8081/api/payments/request/success
    fail_url: http://localhost:8081/api/payments/request/fail

kafka:
  server: "localhost:9092"